### ISSUE TITLE
Problem with rendering results

### ISSUE THREAD

**Issue by upupGuan** [iSach/SoccerNeRFs#1]
hello, thank you for your repo!  I have encountered a problem at  Single Player: Broadcast-style Views experiment. 
I run 
"ns-train k-planes \                                                   # Train K-Planes
    --vis viewer \                                                         # Use the viewer
    --pipeline.model.multiscale-res 1 2 4 8 16 32 \   # New scale (32x)
    --pipeline.datamanager.ist-range 0.75 \              # Modified IST Range
    broadcaststyle-data \                                           # Dataset
    --fps-downsample 4                                             # Read 1 frame every 4
 ” 
and
ns-render --load-config /usr/xieyueyue/experi-soccer/outputs/unamed/k-planes/2024-01-09_215258/config.yml --traj filename --eval-num-rays-per-chunk 65536 --camera-path-filename /usr/xieyueyue/experi-soccer/data/broadcaststyle/camera_paths/broadcaststyle.json

![issue](https://github.com/iSach/SoccerNeRFs/assets/13597662/b93b7839-4bfd-442c-945c-718b3a382c27)

**Comment by upupGuan** [comment]
and Why is your rendering effect larger than my character?  Thank you very much for your answer

**Comment by iSach** [comment]
Hello,

Thanks for being interested in this repo. :) 

These differences in quality for the football might be related to different hyper-parameters. The ones provided in the command that you ran are an example for the README. You can try using ISG perhaps instead of IST. Depending on your available compute and VRAM, you can try:
- Increasing the base resolution (`spacetime_resolution`)
- Using slightly larger feature vectors (`feature_dim`)
- Increasing the field samples (`num_nerf_samples_per_ray`) [*This strongly affects details*]
- Increasing the proposal fields samples (`num_proposal_samples_per_ray`) [*This strongly affects details*]
- I do not recommend going beyond 32 for the multiple resolution scales, as this is already quite large.

Despite all the method improvements, playing with hyperparameters affects quite seriously results in general with NeRFs. Another thing that you could try is playing with boundedness:
- In the model config:
> Set `bounded` to `False`
- In the Data Manager settings:
> Playing with `scene_scale` which scales the scene, and might help get the player in the center to get a better representation.
> If getting poor results, you could try playing with `orientation_method` and `center_method` (both default to None).

I am not sure exactly which hyperparameters were used to render the video that contains the frame you showed. I am looking for the original experiment, but everything was done during an internship, and I could not keep all the files, so I might not have everything. 

> and Why is your rendering effect larger than my character? Thank you very much for your answer

Concerning that, this is related to a different camera path being used. I strongly recommend using the Nerfstudio viewer if you can. You can run it on your computer with NodeJS (https://docs.nerf.studio/developer_guides/viewer/local_viewer.html) and it helps inspecting qualitative details. Similarly, if I find it, I will send a new message.

Cheers,
Sacha.

**Comment by iSach** [comment]
For the football, the video indeed uses a different camera path, but I do not have it anymore, I apologize for this. Using the viewer, it could probably be quite simple to generate a new path that is closer to the player.

For the quality, I could not find the exact hyperparameters (only the titled video file), but it is indeed K-Planes, with multiscale res [1, 2, 4, 8, 16, 36] (goes beyond 32 but it will be very expensive) but more importantly, the image resolution in the data manager is set to 1080p instead of 720p.

> `ns-train ... broadcaststyle-data --downscale-factor 1`

It requires longer training (more iterations) and is more expensive in terms of compute, but this often allows to better capture small details. For the other hyperparameters, I recommend following what I said in my message above, especially the number of samples for each network, and also trying using an unbounded scene.

This is something I wanted to explore more deeply, but I am now working on a quite different area. It could be interesting to find a way to sample areas more efficiently and in a smarter way to use 1080p images without too much compute needed, notably through strategies like IST or ISG. Maybe some other network could process images to weigh the pixels to sample? 

Feel free to ask if you want other details or if my message does not exactly answer your question.

**Comment by upupGuan** [comment]
Thank you very much for your answer!   I will try the above content.

Wishing you many more successes during your PhD!

**Comment by iSach** [comment]
> Thank you very much for your answer! I will try the above content.
> 
> Wishing you many more successes during your PhD!

No problem, I hope it will help as this is only some guidance. Thanks a lot! Wishing you much success too for your Master's degree, and beyond ;)

**Comment by upupGuan** [comment]
Hello, I'm here again to ask you questions, I'm very sorry to bother you, because only I study nerf and 3d gs by myself in my laboratory.
Based on isg and ist, I've made some enhancements, and I need new application scenarios in soccer, so I need to use blender to synthesize a dataset for the new scenarios, but I can't render new scenarios like your dataset as well, so I'd like to ask you about the rendering parameters of your blender.

I readed you describe the way you made your dataset.But I have some questions.
1)Stadium Model.  You're recommended to use this https://www.blendswap.com/blend/7488,but I think you're using this https://www.blendswap.com/blend/10567 .So I use 10567

2)  I'd like to ask you about the rendering parameters of your blender. I rendered the grass less realistic. May I ask what I should do to make the imported model as realistic as yours?
![PixPin_2024-03-20_11-08-03](https://github.com/iSach/SoccerNeRFs/assets/13597662/4937d11f-3f65-4b7c-9949-0fb28b48df71)

**Comment by iSach** [comment]
> Hello, I'm here again to ask you questions, I'm very sorry to bother you, because only I study nerf and 3d gs by myself in my laboratory. Based on isg and ist, I've made some enhancements, and I need new application scenarios in soccer, so I need to use blender to synthesize a dataset for the new scenarios, but I can't render new scenarios like your dataset as well, so I'd like to ask you about the rendering parameters of your blender.
> 
> I readed you describe the way you made your dataset.But I have some questions. 1)Stadium Model. You're recommended to use this https://www.blendswap.com/blend/7488,but I think you're using this https://www.blendswap.com/blend/10567 .So I use 10567
> 
> 2. I'd like to ask you about the rendering parameters of your blender. I rendered the grass less realistic. May I ask what I should do to make the imported model as realistic as yours?
>    ![PixPin_2024-03-20_11-08-03](https://private-user-images.githubusercontent.com/13597662/314368010-4937d11f-3f65-4b7c-9949-0fb28b48df71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzMxODIsIm5iZiI6MTcxMDkzMjg4MiwicGF0aCI6Ii8xMzU5NzY2Mi8zMTQzNjgwMTAtNDkzN2QxMWYtM2Y2NS00YjdjLTk5NDktMGZiMjhiNDhkZjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDExMDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYjc5OWE4ZWI1ZDRkOTFhNmVkMTI5MTM0ZGJhN2E3Y2YxZWVkYThhYTVlOWNkNDI3OGIzMjdiNzBkNWU3YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.57u78Bg3YBL2XWtKQARuMB-mt7-Pm6IpJ-wFnyEsyzE)

Indeed, wrong scene link thanks for noticing. I will fix it.

I think I will upload our full scene but remove the players so that people can have the same camera positions and textures as we modified some Blender settings over time. Notably, I forgot we changed the grass texture, thanks for noticing too.

Can you try the following model with textured grass please?
https://cdn.isach.be/textured_grass.blend

**Comment by iSach** [comment]
@fingertip-dance I've updated [this section](https://github.com/iSach/SoccerNeRFs/blob/master/data/README.md#stadium-model). Feel free to try the other Blender file in case the textured grass still does not have the rendering results you aim for.

**Comment by upupGuan** [comment]
> @fingertip-dance I've updated [this section](https://github.com/iSach/SoccerNeRFs/blob/master/data/README.md#stadium-model). Feel free to try the other Blender file in case the textured grass still does not have the rendering results you aim for.

Thank you! Thank you. You saved me a lot of time! Sincere thanks to you
